version: '2'
services:
  zend-exp:
      build: .
      environment:
          XDEBUG_CONFIG: remote_host=192.168.0.102
      ports:
          - "80:80"
      volumes:
          - "../:/var/www/site"
      restart: always