<div style="width: 744px; margin: auto; border: 1px solid black">
    <table style="width: 644px; margin: auto; border: 1px solid black">
        <tr>
            <td width="50%">Logo</td>
            <td width="50%" style="text-align: right; padding-right: 30px">
                <p>Pro forma</p>
                <p>April 18, 2018</p>
                <p>Pro forma NO: LOC20180206-10</p>
            </td>
        </tr>
    </table>
    <table style="width: 604px; margin: auto; border: 1px solid black">
        <tr>
            <td>
                <p>NEW LINTA AERO ENGINE</p>
                <p>NYBROGATAN 34</p>
                <p>STOCKHOLM, 11439</p>
                <p>Sweden</p>
            </td>
        </tr>
        <tr>
            <td>
                <table width="100%">
                    <tr>
                        <td width="50%">Description</td>
                        <td width="50%">Condition</td>
                    </tr>
                    <tr>
                        <td>Starts</td>
                        <td>April 4th 2018</td>
                    </tr>
                    <tr>
                        <td>Duration [months]</td>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>Concurrent connections*: </td>
                        <td>Up to 2 </td>
                    </tr>
                    <tr>
                        <td>Amber A.I. plugins</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Amber A.I. emails</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Users</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Searches</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>RFQ’s </td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Inventory listings</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Repair Capabilities listings</td>
                        <td>Unlimited</td>
                    </tr>
                    <tr>
                        <td>Public Company Profile</td>
                        <td>Included</td>
                    </tr>
                    <tr>
                        <td>
                            <p>*Concurrent connections stand for the number of users that are able to log onto the
                                platform at the same time. </p>
                        </td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>VAT*</td>
                        <td>0%</td>
                    </tr>
                    <tr>
                        <td>Total due</td>
                        <td>$ 400</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>Special condition: Next year subscription 450 USD</td>
        </tr>
        <tr>
            <td>
                <p>Please choose one of the following payment options. Due date: 24 of April, 2018</p>
                <table>
                    <tr>
                        <td width="50%">Wire transfer</td>
                        <td width="50%">Credit card</td>
                    </tr>
                    <tr>
                        <td>
                            <p>Company name: <b>JSC Locatory.com</b></p>
                            <p>Company Address: Smolensko st. 10, LT-03201 Vilnius, Lithuania </p>
                            <p>Company code: 302572273 </p>
                            <p>VAT code: LT100006029014 </p>
                            <p>Bank: AB DnB Nord bank </p>
                            <p>Bank address: J. Basanaviciaus st. 26, 03601 Vilnius, Lithuania </p>
                            <p>Bank account:  LT094010049500985902</p>
                            <p>SWIFT AGBLLT2X</p>
                        </td>
                        <td>
                            <p>Please follow the link o make payment by Credit Card: </p>
                            <p>https://www.locatory.com/v5/index.php/en/billing/?coupon=0201F-8C243-C243A</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <td width="50%">
                            For any enquiries regarding this payment please, contact:
                            <a href="#">ilona.orvidiene@locatory.com</a>
                        </td>
                        <td width="50%"></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            By making a payment you accept the Site usage policy which can be downloaded at:
                            <a href="#">www.locatory.com/legal-issues</a>
                        </td>

                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <table style="width: 644px; margin: auto; border: 1px solid black">
        <tr>
        <tr>
            <td>
                <p style="text-align: center">JSC „Locatory.com“</p>
                <table width="100%">
                    <tr>
                        <td width="25%">
                            <p>Company code: 302572273</p>
                            <p>VAT code: LT100006029014</p>
                        </td>
                        <td width="25%">
                            <p>Smolensko st. 10, LT-03201,</p>
                            <p>Vilnius, Lithuania</p>
                        </td>
                        <td width="25%">
                            <p>Tel. +370 5 252 5500</p>
                            <p>Fax +370 5 252 5501</p>
                        </td>
                        <td width="25%">
                            <p>Email: info@locatory.com</p>
                            <p>Website: locatory.com</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
